env:
    browser: true
    node: true
    jest: true

parserOptions:
    ecmaVersion: 2018
    impliedStrict: true
    sourceType: module

extends:
    - eslint:recommended
    - plugin:react/recommended

settings:
    react:
        version: '16.0'

rules:
    semi:
        - error
        - never
    indent:
        - error
        - 4
        - SwitchCase: 1
