parser: babel-eslint

env:
    browser: true
    node: true

parserOptions:
    ecmaVersion: 2018
    impliedStrict: true
    sourceType: module

extends:
    - eslint:recommended
    - plugin:react/recommended

settings:
    react:
        version: '16.5.2'

rules:
    indent:
        - error
        - 4
        - SwitchCase: 1
